---
blueprint:
    name: Disable obstacle avoidance on selected room
    description: Disable/Enable obstacle avoidance according to the robots current room
    domain: automation
    source_url: https://github.com/Strangeluv/dreame-vacuum/blob/master/blueprints/automation/disable_obstacle_avoidance_on_selected_room.yaml
    input:
        vacuum:
            name: Vacuum Entity
            selector:
                entity:
                    domain: vacuum
                    integration: dreame_vacuum
        room_id:
            name: Selected room id
            selector:
                number:
                    min: 1
                    max: 60
                    mode: box


mode: single

variables:
    room_id: !input room_id
    vacuum: !input vacuum
    vacuum_name: "{{ vacuum.split('.')[1] }}"
    current_room: "sensor.{{ vacuum_name }}_current_room"
    switch: "switch.{{ vacuum_name }}_obstacle_avoidance"
    tight: "switch.{{ vacuum_name }}_tight_mopping"

trigger:
  - platform: state
    entity_id: !input vacuum

condition: "{{ (not is_state(current_room, 'unavailable') and ((is_state(switch, 'on') and is_state_attr(current_room, 'room_id', room_id)) or is_state(switch, 'off'))) }}"

action:
    service: "switch.turn_{{ 'off' if is_state_attr(current_room, 'room_id', room_id) else 'on' }}"
    target:
        entity_id: "{{ switch }}"
    service: "switch.turn_{{ 'on' if is_state_attr(current_room, 'room_id', room_id) else 'off' }}"
    target:
        entity_id: "{{ tight }}"
    data: {}
